### ISSUE TITLE
Path has no method 'isAbsolute'

### ISSUE THREAD

**Issue by mderazon** [substack/html-inline#12]
Running v1.1.2 on node v0.10.37 (old, i know...)
```
TypeError: Object #<Object> has no method 'isAbsolute'
    at fix (/myapp/node_modules/node-deeplink/node_modules/html-inline/index.js:79:17)
    at /myapp/node_modules/node-deeplink/node_modules/html-inline/index.js:13:24
    at Match._fn (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/index.js:96:17)
    at DestroyableTransform.write [as _transform] (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/html-select/lib/match.js:37:18)
    at DestroyableTransform.Transform._read (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Match.Pipeline._write (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/html-select/node_modules/stream-splicer/index.js:73:22)
    at Pipeline._write (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/html-select/node_modules/stream-splicer/index.js:73:22)
    at doWrite (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Pipeline.Writable.write (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at DestroyableTransform.ondata (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at DestroyableTransform.emit (events.js:95:17)
    at readableAddChunk (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at DestroyableTransform.Readable.push (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DestroyableTransform.Transform.push (/myapp/node_modules/node-deeplink/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_transform.js:145:32) 
```

**Comment by pguth** [comment]
I had a even older version. [Updating Node](https://nodejs.org/en/download/package-manager/) helped!

**Comment by abelnation** [comment]
I'm unforatunately tied to an older version of node.  Poly-filling this method would be appreciated.

**Comment by abelnation** [comment]
see #15
